apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chroma-pvc
  namespace: hr-interview
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: hr-interview
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 20Gi
